controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadCaster


diff_cont:
  ros__parameters:
    publish_rate: 30.0

    base_frame_id: base_footprint

    left_wheel_names: ['base_left_back_wheel_joint', 'base_left_front_wheel_joint']
    right_wheel_names: ['base_right_back_wheel_joint', 'base_right_front_wheel_joint']
    wheel_separation: 1.971
    wheel_radius: 0.5

    use_stamped_vel: false