controller_manager:
  ros__parameters:
    update_rate: 10


    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster



diff_cont:
  ros__parameters:

    publish_rate: 10.0

    base_frame_id: base_footprint
    wheels_per_side: 2

    left_wheel_names: ["base_left_front_wheel_joint", "base_left_back_wheel_joint"]
    right_wheel_names: ["base_right_front_wheel_joint", "base_right_back_wheel_joint"]
    odom_frame_id: odom

    wheel_separation: 0.145
    wheel_radius: 0.03


    open_loop: true
    enable_odom_tf: true

    # cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    use_stamped_vel: false

